:- op(1200, xfx, :+).

answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Barcelona International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Adolfo Suárez Madrid–Barajas Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Paris-Orly Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Malpensa International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Leonardo da Vinci–Fiumicino Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Ben Gurion International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Keflavik International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Humberto Delgado Airport (Lisbon Portela Airport)","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Geneva Cointrin International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Zürich Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Narita International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Brussels Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Hong Kong International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Indira Gandhi International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Beijing Capital International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Shanghai Pudong International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Hamburg Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Düsseldorf Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Munich Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Berlin-Tegel Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Manchester Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","London Heathrow Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Dublin Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Copenhagen Kastrup Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Oslo Lufthavn","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Stockholm-Arlanda Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Ronald Reagan Washington National Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Narita International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Beijing Capital International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Shanghai Pudong International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Incheon International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Chubu Centrair International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","London Heathrow Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Tampa International Airport","Zürich Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Tampa International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Tampa International Airport","London Gatwick Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Adolfo Suárez Madrid–Barajas Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Leonardo da Vinci–Fiumicino Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Zürich Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Narita International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Brussels Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Düsseldorf Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Munich Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Incheon International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Manchester Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","London Heathrow Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Dublin Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Barcelona International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Adolfo Suárez Madrid–Barajas Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Leonardo da Vinci–Fiumicino Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Ben Gurion International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Humberto Delgado Airport (Lisbon Portela Airport)","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Zürich Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Brussels Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Munich Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Eleftherios Venizelos International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Manchester Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","London Heathrow Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Dublin Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Adolfo Suárez Madrid–Barajas Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Leonardo da Vinci–Fiumicino Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Vienna International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Zürich Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Atatürk International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Narita International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Brussels Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Hong Kong International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Indira Gandhi International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Beijing Capital International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Shanghai Pudong International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Düsseldorf Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Munich Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Berlin-Tegel Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Incheon International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Manchester Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","London Heathrow Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Dublin Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Copenhagen Kastrup Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Warsaw Chopin Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Stockholm-Arlanda Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Baltimore/Washington International Thurgood Marshall Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Baltimore/Washington International Thurgood Marshall Airport","London Heathrow Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Minneapolis-St Paul International/Wold-Chamberlain Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Minneapolis-St Paul International/Wold-Chamberlain Airport","Narita International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Minneapolis-St Paul International/Wold-Chamberlain Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Minneapolis-St Paul International/Wold-Chamberlain Airport","London Heathrow Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Minneapolis-St Paul International/Wold-Chamberlain Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","Leonardo da Vinci–Fiumicino Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","Munich Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","London Heathrow Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","Dublin Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Orlando International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Orlando International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Orlando International Airport","Manchester Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Orlando International Airport","London Gatwick Airport","Helsinki Vantaa Airport"])).
answer('urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Orlando International Airport","Dublin Airport","Helsinki Vantaa Airport"])).

% proof steps
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],A)),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Barcelona International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_1229','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Adolfo Suárez Madrid–Barajas Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_1382','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_1386','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Paris-Orly Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_1524','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Malpensa International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_1555','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Leonardo da Vinci–Fiumicino Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_1590','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Ben Gurion International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_16','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Keflavik International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_1638','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Humberto Delgado Airport (Lisbon Portela Airport)","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_1665','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Geneva Cointrin International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_1678','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Zürich Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_2279','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Narita International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_302','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Brussels Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_3077','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Hong Kong International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_3093','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Indira Gandhi International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_3364','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Beijing Capital International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_340','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_3406','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Shanghai Pudong International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_342','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Hamburg Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_345','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Düsseldorf Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_346','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Munich Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_351','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Berlin-Tegel Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_478','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Manchester Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_507','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","London Heathrow Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_580','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_599','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Dublin Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_609','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Copenhagen Kastrup Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_644','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Oslo Lufthavn","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3494','urn:example:airroutes:AIRPORT_737','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Newark Liberty International Airport","Stockholm-Arlanda Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3520','urn:example:airroutes:AIRPORT_3797','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Ronald Reagan Washington National Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3645','urn:example:airroutes:AIRPORT_1382','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3645','urn:example:airroutes:AIRPORT_2279','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Narita International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3645','urn:example:airroutes:AIRPORT_3364','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Beijing Capital International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3645','urn:example:airroutes:AIRPORT_340','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3645','urn:example:airroutes:AIRPORT_3406','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Shanghai Pudong International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3645','urn:example:airroutes:AIRPORT_3797','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3645','urn:example:airroutes:AIRPORT_3930','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Incheon International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3645','urn:example:airroutes:AIRPORT_3942','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Chubu Centrair International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3645','urn:example:airroutes:AIRPORT_507','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","London Heathrow Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3645','urn:example:airroutes:AIRPORT_580','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Detroit Metropolitan Wayne County Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3646','urn:example:airroutes:AIRPORT_1678','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Tampa International Airport","Zürich Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3646','urn:example:airroutes:AIRPORT_3797','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Tampa International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3646','urn:example:airroutes:AIRPORT_502','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Tampa International Airport","London Gatwick Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_1229','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Adolfo Suárez Madrid–Barajas Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_1382','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_1555','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Leonardo da Vinci–Fiumicino Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_1678','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Zürich Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_2279','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Narita International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_302','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Brussels Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_340','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_345','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Düsseldorf Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_346','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Munich Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_3797','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_3930','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Incheon International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_478','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Manchester Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_507','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","London Heathrow Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_580','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3682','urn:example:airroutes:AIRPORT_599','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Hartsfield Jackson Atlanta International Airport","Dublin Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_1218','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Barcelona International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_1229','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Adolfo Suárez Madrid–Barajas Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_1382','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_1555','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Leonardo da Vinci–Fiumicino Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_1590','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Ben Gurion International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_1638','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Humberto Delgado Airport (Lisbon Portela Airport)","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_1678','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Zürich Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_302','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Brussels Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_340','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_346','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Munich Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_3797','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_3941','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Eleftherios Venizelos International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_478','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Manchester Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_507','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","London Heathrow Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_580','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3752','urn:example:airroutes:AIRPORT_599','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Philadelphia International Airport","Dublin Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_1229','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Adolfo Suárez Madrid–Barajas Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_1382','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_1555','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Leonardo da Vinci–Fiumicino Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_1613','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Vienna International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_1678','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Zürich Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_1701','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Atatürk International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_2279','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Narita International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_302','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Brussels Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_3077','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Hong Kong International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_3093','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Indira Gandhi International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_3364','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Beijing Capital International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_340','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_3406','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Shanghai Pudong International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_345','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Düsseldorf Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_346','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Munich Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_351','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Berlin-Tegel Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_3797','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_3930','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Incheon International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_478','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Manchester Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_507','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","London Heathrow Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_580','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_599','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Dublin Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_609','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Copenhagen Kastrup Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_679','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Warsaw Chopin Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3830','urn:example:airroutes:AIRPORT_737','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Chicago O'Hare International Airport","Stockholm-Arlanda Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3849','urn:example:airroutes:AIRPORT_3797','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Baltimore/Washington International Thurgood Marshall Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3849','urn:example:airroutes:AIRPORT_507','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Baltimore/Washington International Thurgood Marshall Airport","London Heathrow Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3858','urn:example:airroutes:AIRPORT_1382','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Minneapolis-St Paul International/Wold-Chamberlain Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3858','urn:example:airroutes:AIRPORT_2279','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Minneapolis-St Paul International/Wold-Chamberlain Airport","Narita International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3858','urn:example:airroutes:AIRPORT_3797','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Minneapolis-St Paul International/Wold-Chamberlain Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3858','urn:example:airroutes:AIRPORT_507','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Minneapolis-St Paul International/Wold-Chamberlain Airport","London Heathrow Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3858','urn:example:airroutes:AIRPORT_580','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Minneapolis-St Paul International/Wold-Chamberlain Airport","Amsterdam Airport Schiphol","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3876','urn:example:airroutes:AIRPORT_1382','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","Charles de Gaulle International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3876','urn:example:airroutes:AIRPORT_1555','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","Leonardo da Vinci–Fiumicino Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3876','urn:example:airroutes:AIRPORT_340','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3876','urn:example:airroutes:AIRPORT_346','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","Munich Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3876','urn:example:airroutes:AIRPORT_3797','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3876','urn:example:airroutes:AIRPORT_507','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","London Heathrow Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3876','urn:example:airroutes:AIRPORT_599','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Charlotte Douglas International Airport","Dublin Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3878','urn:example:airroutes:AIRPORT_340','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Orlando International Airport","Frankfurt am Main Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3878','urn:example:airroutes:AIRPORT_3797','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Orlando International Airport","John F Kennedy International Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3878','urn:example:airroutes:AIRPORT_478','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Orlando International Airport","Manchester Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3878','urn:example:airroutes:AIRPORT_502','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Orlando International Airport","London Gatwick Airport","Helsinki Vantaa Airport"]),true).
step((true:+'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],['urn:example:airroutes:AIRPORT_3878','urn:example:airroutes:AIRPORT_599','urn:example:airroutes:AIRPORT_421'])),'urn:example:discover'(["Manchester-Boston Regional Airport","Helsinki Vantaa Airport"],["Manchester-Boston Regional Airport","Orlando International Airport","Dublin Airport","Helsinki Vantaa Airport"]),true).
