#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
NORMAL="\e[0;39m"

OK=0
FAILED=0

echo -e "${YELLOW}--------------------------------------${NORMAL}"
echo -e "${YELLOW}running eyelog examples and test cases${NORMAL}"
echo -e "${YELLOW}using eyelog $(../eyelog-scryer-prolog 2>&1 | awk '{ print $2 }') and scryer $(scryer-prolog --version 2>&1 | sed 's/-.*//')${NORMAL}"
echo -e "${YELLOW}--------------------------------------${NORMAL}"
echo ""

pad () {
    [ "$#" -gt 1 ]
    [ -n "$2" ]
    printf "%$2.${2#-}s" "$1"
}

begin=$(($(date +%s)))
for file in *.pl
do
    [[ "${file}" != eyelog.pl ]] || continue
    echo -en "$(pad "${file}" -26)"
    start=$(($(date +%s%N)/1000000))
    ../eyelog-scryer-prolog "${file}" > output-scryer-prolog/${file}
    end=$(($(date +%s%N)/1000000))
    echo -en "${YELLOW}$(pad "`expr $end - $start` msec" 10)${NORMAL} "
    if [[ $(git diff output-scryer-prolog/${file} | wc -l) -eq 0 ]]; then
        echo -e "${GREEN}OK${NORMAL}"
        ((OK++))
    else
        echo -e "${RED}FAILED${NORMAL}"
        ((FAILED++))
    fi
done
end=$(($(date +%s)))
echo ""

echo -e "${YELLOW}`expr $end - $begin` sec${NORMAL} ${GREEN}${OK} OK${NORMAL} ${RED}${FAILED} FAILED${NORMAL}"
if [[ ${FAILED} -eq 0 ]]; then
    exit 0
else
    exit 2
fi
