:- op(1200, xfx, :+).

answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66',A])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12',A])).

% proof steps
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66',C]),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12',C]),true).
