:- op(1200, xfx, :+).

answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9'])).
answer('urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9'])).

% proof steps
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6','urn:example:i6']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84','urn:example:i75','urn:example:i84']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9','urn:example:i12','urn:example:i66','urn:example:i9']),true).
step((true:+'urn:example:cycle'(A,B)),'urn:example:cycle'('urn:example:i0',['urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9','urn:example:i12','urn:example:i9']),true).
